name: Bug Report
description: Report a bug or documentation error
title: "[Bug]: "
labels: ["🚨 new::bug"]
projects: ["deven-org/3"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a bug or a documentation error, please [check if the issue already exists](https://github.com/deven-org/B01LER-Kitchen/issues).
        
        ---
        
        Thanks for taking the time to fill out this bug report! We will do our best to reply to new issues within a week.
  - type: dropdown
    id: bug-type
    attributes:
      label: What is affected?
      description: You can select multiple options.
      multiple: true
      options:
        - Component
        - Accessibility
        - Token System
        - Documentation
        - Other (please specify in the description)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Also tell us, what did you expect to happen?
      placeholder: "When I do ..., I would expect ..., instead ... happens."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
      value: |
        1. Step 1
        2. ...
  - type: input
    id: version
    attributes:
      label: Affected version(s)
      description: What version of B01LER are you running? If the issue was not affecting a previous version, which was it?
      placeholder: "vX.X.X with issue, vX.X.X without issue"
  - type: textarea
    id: os-browser-env
    attributes:
      label: Operating system / Browser / Environment
      description: "Which operating system and browser do you use? Please provide the version as well. If the bug affects a command-line tool, please add this information as well."
      placeholder: "OS: macOS Sonoma 14.2.1 (23C71), Browser: Chrome 121.0.6167.85, Node: 18.17.0, yarn: 4.0.2"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/deven-org/B01LER-Kitchen/blob/develop/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
