name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["🚨 new::bug"]
projects: ["deven-org/3"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please [check if your issue already exists](https://github.com/deven-org/B01LER-Kitchen/issues).
        
        ---
        
        Thanks for taking the time to fill out this bug report! We will do our best to reply to new issues within a week.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Sonoma 14.2.1 (23C71)"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other (please specify in the description)
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of B01LER are you running?
      placeholder: "v0.1.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/deven-org/B01LER-Kitchen/blob/develop/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label:
            I checked the [current issues](https://github.com/deven-org/B01LER-Kitchen/issues) for duplicate requests
