name: Eslint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Enable Corepack
        run: corepack enable

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn lint
